title: WABI 2025
preposition: ''
description: >-
  WABI Conference on Algorithms in Bioinformatics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wabiconf.github.io/2025" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: True

  main:
    logo:
      img: banner.jpg

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  talks:
    # Talk categories
    main_categories:
      - name: Proceedings talks
        color: info
      - name: Highlight talks
        color: success

  location:
    url: '/location'
    map: true

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true

  # Navigation bar
  navigation:
    logo:
      name: WABI 2025
      # img: ''
      url: 'https://wabiconf.github.io/2025'
    breakpoint: md
    links:
      - name: Program Committee
        relative_url: /program_committee/
      #- name: Program
      #  relative_url: /program/
      - name: Talks
        relative_url: /talks/
      #- name: Speakers
      #  relative_url: /speakers/
      - name: Location
        relative_url: /location/
